In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold,ShuffleSplit,cross_val_score

In [2]:
shuju3= pd.read_excel("LIPIRIN_TOP30% 1+_identify.xlsx",index_col=0)

In [3]:
shuju3_ =shuju3.copy()

In [4]:
shuju3_

CLASS2  Hypoxanthine
MetaboName                      
B60              1  1.780298e+07
B63              1  1.586566e+07
B64              1  2.267567e+07
B65              1  7.030324e+09
B67              1  2.816587e+07
B75              1  1.740545e+07
B77              1  2.279251e+07
B83              1  7.824715e+07
B85              1  5.671875e+09
B90              1  2.940433e+09
B98              1  2.991771e+09
B46              0  1.595924e+10
B59              0  5.711871e+07
B62              0  7.448535e+09
B74              0  1.789717e+07
B76              0  8.952675e+07
B80              0  9.259466e+09
B82              0  6.770671e+09
B88              0  1.455464e+10
B92              0  9.172512e+09
B96              0  3.819459e+09
B97              0  6.511077e+09

In [5]:
FFS3 =shuju3_.drop(columns=['CLASS2'])

In [6]:
FFS3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22 entries, B60 to B97
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Hypoxanthine  22 non-null     float64
dtypes: float64(1)
memory usage: 352.0+ bytes


In [7]:
target3 = shuju3_.CLASS2

In [8]:
transfer = StandardScaler()

In [9]:
tezheng3 = transfer.fit_transform(FFS3)

In [10]:
tezheng3

array([[-0.87381382],
       [-0.87421817],
       [-0.87279682],
       [ 0.5898071 ],
       [-0.87165093],
       [-0.87389679],
       [-0.87277243],
       [-0.86119819],
       [ 0.30627793],
       [-0.26381599],
       [-0.25310097],
       [ 2.45340932],
       [-0.86560803],
       [ 0.67709419],
       [-0.87379416],
       [-0.85884397],
       [ 1.05506337],
       [ 0.53561349],
       [ 2.16024747],
       [ 1.03691468],
       [-0.08034965],
       [ 0.48143237]])

In [11]:
sss3 = ShuffleSplit(n_splits=10, test_size=0.2,random_state=99)

In [12]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.svm import SVC

In [13]:
CCs2 = np.logspace(-3,3,1000)

In [14]:
param_distributions={'C': np.logspace(-3,3,1000),'gamma': np.logspace(-3,3,200), 'kernel': ['linear', 'rbf']}

In [15]:
svc_clf = SVC()

In [16]:
random_search =RandomizedSearchCV(svc_clf, param_distributions, cv=sss3, n_iter=20000)

In [17]:
random_search.fit(tezheng3, target3)

RandomizedSearchCV(cv=ShuffleSplit(n_splits=10, random_state=99, test_size=0.2, train_size=None),
                   estimator=SVC(), n_iter=20000,
                   param_distributions={'C': array([1.00000000e-03, 1.01392541e-03, 1.02804473e-03, 1.04236067e-03,
       1.05687597e-03, 1.07159340e-03, 1.08651577e-03, 1.10164595e-03,
       1.11698682e-03, 1.13254132e-03, 1.14831241e-03, 1.16430313e-03,
       1.18051653e-03,...
       2.02550194e+02, 2.17111795e+02, 2.32720248e+02, 2.49450814e+02,
       2.67384162e+02, 2.86606762e+02, 3.07211300e+02, 3.29297126e+02,
       3.52970730e+02, 3.78346262e+02, 4.05546074e+02, 4.34701316e+02,
       4.65952567e+02, 4.99450512e+02, 5.35356668e+02, 5.73844165e+02,
       6.15098579e+02, 6.59318827e+02, 7.06718127e+02, 7.57525026e+02,
       8.11984499e+02, 8.70359136e+02, 9.32930403e+02, 1.00000000e+03]),
                                        'kernel': ['linear', 'rbf']})

In [18]:
random_search.best_params_

{'kernel': 'rbf', 'gamma': 1000.0, 'C': 21.395888713434214}

In [19]:
random_search.best_score_

0.78

In [20]:
random_search.best_estimator_

SVC(C=50.431594871713585, gamma=0.7316807143427192)

In [21]:
SVC3=SVC(C=50.431594871713585,kernel='rbf',gamma=0.7316807143427192)

In [22]:
SVC3.fit(tezheng3, target3)

SVC(C=50.431594871713585, gamma=0.7316807143427192)

In [23]:
SVC3.score(tezheng3, target3)

0.9565217391304348

In [24]:
SVC3.coef_

AttributeError: coef_ is only available when using a linear kernel

In [32]:
shuju23= pd.read_excel("LIPIRIN-Top30%-IDE-Target-1+.xlsx",index_col=0)

In [33]:
shuju23_ =shuju23.copy()

In [34]:
shuju23_

Lithocholic acid  sulfate  CLASS2
Name                                      
KXExp1                22612.343890     NaN
KXExp2                40279.004780     NaN
KXExp3                65010.569810     NaN
KXExp4                77731.920000     NaN
KXExp5                28266.384000     NaN
KXExp6                79147.656000     NaN
KXExp7               141335.736000     NaN
KXExp8               211933.140200     NaN
KXExp9               180083.275800     NaN
KXExp10               34626.384000     NaN
KXExp11               56535.311930     NaN
KXExp12              334253.616000     NaN
KXExp13               79140.369710     NaN
KXExp14               38155.753440     NaN
KYExp16                3533.615897     NaN
KYExp17                9893.616000     NaN
KYExp18               12719.999900     NaN
KYExp19                4946.808000     NaN
KYExp20                4239.576000     NaN
KYExp21                2120.424000     NaN
KYExp25                8479.153055     NaN
KYExp26               12014.038940     NaN
KYExp27                6360.418569     NaN
KYExp28                9893.616000     NaN
CXExp29                3533.616518     NaN
CXExp33               12012.767600     NaN
CXExp34               10600.848000     NaN
CXExp35               10599.576000     NaN
CXExp36               14840.424000     NaN
CXExp37               23319.576000     NaN
CXExp38               12012.758780     NaN
CXExp39               34627.656000     NaN
CXExp40                7774.464000     NaN
CXExp41               14840.386070     NaN
CXExp42                9186.384000     NaN
CYExp43               13427.231940     NaN
CYExp44                8480.424000     NaN
CYExp45                7773.192000     NaN
CYExp46               17665.535890     NaN
CYExp47               13423.282130     NaN
CYExp48                7067.231905     NaN
CYExp49                5652.768000     NaN
CYExp51               10599.576000     NaN
CYExp53                4240.848000     NaN
CYExp56                7067.231673     NaN
KYExp60                7067.232000     NaN

In [35]:
FFS23 =shuju23_.drop(columns=['CLASS2'])

In [36]:
FFS23.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, KXExp1 to KYExp60
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Lithocholic acid  sulfate  46 non-null     float64
dtypes: float64(1)
memory usage: 736.0+ bytes


In [37]:
target23 = shuju23_.CLASS2

In [38]:
transfer = StandardScaler()

In [39]:
tezheng23 = transfer.fit_transform(FFS23)

In [40]:
tezheng23

array([[-0.23528594],
       [ 0.04633531],
       [ 0.440577  ],
       [ 0.64336589],
       [-0.14515584],
       [ 0.66593389],
       [ 1.65726355],
       [ 2.78264481],
       [ 2.27493151],
       [-0.04377216],
       [ 0.30547435],
       [ 4.7325348 ],
       [ 0.66581775],
       [ 0.01248892],
       [-0.53941671],
       [-0.43803303],
       [-0.39297812],
       [-0.51688926],
       [-0.52816312],
       [-0.56194416],
       [-0.46058074],
       [-0.40423172],
       [-0.49435513],
       [-0.43803303],
       [-0.5394167 ],
       [-0.40425199],
       [-0.42675916],
       [-0.42677944],
       [-0.3591768 ],
       [-0.22401207],
       [-0.40425213],
       [-0.04375189],
       [-0.47181407],
       [-0.3591774 ],
       [-0.44930689],
       [-0.38170425],
       [-0.46056048],
       [-0.47183435],
       [-0.31414217],
       [-0.38176722],
       [-0.48308794],
       [-0.50563567],
       [-0.42677944],
       [-0.52814285],
       [-0.48308794],
       [-0

In [41]:
test_predict = SVC3.predict(tezheng23)
test_predict

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int64)